on:
  schedule: 
    - cron: "0 4 * * 1"
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  docker:
    uses: lab-xyz/workflows/.github/workflows/docker-build.yml@v1
    secrets: inherit
